status checks

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -1,26 +1,32 @@
-name: Static check Functions
+name: Status Check Functions
 on: [push]
 
 jobs:
-    job-1:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Step 1
-              run: |
-                sleep 20
-            - name: Runs on Faulure
-            # this step will run only if any of the previous steps have failed
-              if: failure()
-              run: |
-                    echo "This step runs on failure of previous steps."
-            - name: Always Runs
-            # if: Success() || failure()
-              if: always()
-              run: |
-                    echo "This step always runs regardless of previous step results."
-    job-2:
-        runs-on: ubuntu-latest
-        needs: job-1
-        if: failure()
-        steps:
-          - run: echo 'Job 2'
+  job-1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step 1
+        run: sleep 20
+      - name: Step 2
+        id: step-2
+        run: exit 1
+      - name: Runs on Failure
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
+      - name: Runs on Success
+        # This is not needed (DEFAULT BEAHAVIOUR)
+        if: success()
+        run: echo 'Runs on Success'
+      - name: Always Runs
+        # if: success() || failure()
+        if: always()
+        run: echo 'Always Runs'
+      - name: Runs When Cancelled
+        if: cancelled()
+        run: echo 'Runs on Cancelled'
+  job-2:
+    runs-on: ubuntu-latest
+    needs: job-1
+    if: failure()
+    steps:
+      - run: echo 'Job 2'
